### PR TITLE
feat(awc): add loaders for local fonts

### PR DESCRIPTION
**Pull request by vlados**
** PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ng-seed/angular-webpack-config/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

** PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```
Relates  to #33

### CODE REVIEW

**Comment by fulls1z3** [comment]
@vlados I was in a training session last week, hence could not review your changes yet. Your contributions look cool by the way 👍 

This week I will review this together with some enhancements I previously made and probably have a new release.

**Comment by vlados** [comment]
Check out it in my forked repo. I've made some changes so now the fonts and images are loaded :)

**Comment by fulls1z3** [comment]
@vlados I see some changes with this PR and your fork. I'll try to merge this PR and release, but the changes on your work will be excluded by the release.

**Comment by fulls1z3** [comment]
@vlados I'm sorry but I looked on the list of commits list in reverse order, things seem fine now 😄

**Pull request merged**
